# This file contains properties that are used for "DEV" environment

http:
  host:                             "localhost"
  port:                             "7081"
  
# Supported destinations by Mule United Airport [defined in RAML]
valid:
  destinationCities:                 "ALL, LAX, CLE, SFO, PDX, PDF"
  
# American REST service properties
american:
  rest:
    hostName:                         "mu.mule-training.com"
    portNumber:                       "80"
    basePath:                         "/american"
    protocol:                         "HTTP"
    responseTimeout:                  "3000"
    clientId:                         "2b6e1d0a4bda4fb6a986766395f721ac"
    clientSecret:                     "5727697f45b1491986d748F2A180C95C"
    

# American REST service properties
#american:
#  rest:
#    hostName:                         "proxy-sahil-american-flights-sapi-sh91um.5sc6y6-4.usa-e2.cloudhub.io"
#    portNumber:                       "443"
#    basePath:                         "/"
#    protocol:                         "HTTPS"
#    responseTimeout:                  "3000"
#    clientId:                         "e35d0150ce614438936ad0a3a7569602"
#    clientSecret:                     "140127d52Dbc41f68a5E693837a799e5"